/*
 * This source file was generated by the Gradle 'init' task
 */
package java_calculator;

public class App {

    public static void main(String[] args) {
        Addition add1 = new Addition();
        double result = add1.execute(15, 15);
        System.out.println(result);
    }
}
