/*
 * This source file was generated by the Gradle 'init' task
 */
package java_calculator;

public class App {

    public static void main(String[] args) {
        CalculatorEngine engine = new BasicCalculatorEngine();

        System.out.println("=== TEST 1: Operazione Semplice (10 + 5 =) ===");
        engine.enterNumber(10);
        engine.setOp("+");
        engine.enterNumber(5);
        double result1 = engine.calculate();

        System.out.println("Risultato atteso: 15.0");
        System.out.println("Risultato ottenuto: " + result1);
        System.out.println("Valore corrente sul display: " + engine.getCurrentValue());
        System.out.println();

        System.out.println("=== TEST 2: Operazioni in Catena (10 + 5 - 3 =) ===");
        // Resettiamo la calcolatrice prima del secondo test
        engine.clear();

        engine.enterNumber(10);
        engine.setOp("+");
        engine.enterNumber(5);

        // Premendo il secondo operatore "-", il motore deve calcolare (10 + 5) parziale
        // = 15
        engine.setOp("-");
        System.out.println("Totale parziale dopo '+': " + engine.getCurrentValue()); // Dovrebbe mostrare 15.0

        engine.enterNumber(3);
        double result2 = engine.calculate(); // Esegue 15 - 3

        System.out.println("Risultato atteso finale: 12.0");
        System.out.println("Risultato ottenuto: " + result2);
        System.out.println();

        System.out.println("=== TEST 3: Verifica tasto Clear ===");
        engine.clear();
        System.out.println("Valore dopo il clear (atteso 0.0): " + engine.getCurrentValue());
    }
}
